.github/workflows/semantic-pr.yml
=> ci: Enforce semantic PRs

.github/workflows/github-projects-for-openfoodfacts-design.yml, .github/workflows/github-projects.yml
=> ci: auto add to github projects

README.md, doc/references/taxonomy-parser.md
=> docs: taxonomy parser reference

.gitignore, doc/how-to-guides/develop-with-neo4j.md, docker-compose.yml
Add a neo4j database using docker-compose (basic setup for now).
=> build: add neo4j with docker

doc/references/taxonomy-parser.md
fix typo… signaled by @BryanH01
=> doc: fix typo

backend/sample/test-neo4j.json, doc/references/taxonomy-parser.md
Documentation + sample part for
- #28
=> docs: introduce main_language property on entries

.github/workflows/auto-assign-pr.yml
=> ci: Auto-assign PRs

parser/openfoodfacts_taxonomy_parser/parser.py
- Adding error logs : reading errors, entries with same id, parent not found
=> feat: add error logs to parser

parser/openfoodfacts_taxonomy_parser/parser.py, parser/openfoodfacts_taxonomy_parser/unparser.py, parser/tests/integration/test_parse_unparse_integration.py, parser/tests/integration/test_parser_integration.py
- Script to write a .txt file from the nodes in neo4j database
=> feat: Create unparser.py

.github/workflows/github-projects.yml
- ci: disable adding to GHP for dependabot
=> ci: disable adding to GHP for dependabot

doc/introduction/setup-dev.md
Describing installation process without docker.
=> docs: install without docker

README.md
=> docs: screenshots in readme

taxonomy-editor-frontend/package-lock.json, taxonomy-editor-frontend/package.json, taxonomy-editor-frontend/src/pages/editentry/AccumulateAllComponents.jsx, taxonomy-editor-frontend/src/pages/editentry/ListAllEntryProperties.jsx, taxonomy-editor-frontend/src/pages/editentry/ListAllNonEntryInfo.jsx, taxonomy-editor-frontend/src/pages/editentry/ListEntryChildren.jsx, taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx
- The frontend requires a unique key for displaying each tag of a stopword or entry
- The frontend generates a unique key for each node object after fetch
=> fix: Add UUIDs after fetching node

backend/editor/entries.py
- Used session.run() instead of get_current_transaction().run()
=> fix: Change session to transactions

.env, conf/nginx.conf, docker-compose.yml, taxonomy-editor-frontend/src/constants.js
=> build: improve api host discovery

backend/editor/api.py, backend/editor/entries.py
- Fetches all root nodes in given taxonomy
- Frontend will render these root nodes for user's convenience
=> feat: Add new endpoint for fetching root nodes

.github/workflows/pull_request.yml, backend/Dockerfile, docker/dev.yml
=> feat: add new user with USER_GID parameter & replace root user

.github/labeler.yml
=> ci: update labeler

taxonomy-editor-frontend/src/pages/allentries/index.jsx, taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx, taxonomy-editor-frontend/src/pages/search/SearchResults.jsx
Added Autocomplete for selecting language code wherever necessary using autocomplete component of MUI.
Fixes #107
=> feat: added autocomplete for language codes

backend/editor/api.py, backend/editor/entries.py, parser/openfoodfacts_taxonomy_parser/parser.py
- Add all warnings and errors to a node in Neo4j
- Fixes #57
=> feat: Update parser to add a neo4j parsing errors node

conf/nginx.conf, docker/dev.yml
=> build: fix confs

.github/workflows/release-please.yml
=> ci: add release please

backend/editor/api.py, backend/editor/entries.py
- Branch name containing hyphens were not normalized
- All API functions and variables converted to snake case for readability
=> fix: Normalize '-' characters + fix: Convert to snake_case

backend/editor/settings.py, conf/nginx.conf, docker/dev.yml
we have to redirect unknown url to index.html so that react app can handle them.
=> fix: nginx config allows app page reload

taxonomy-editor-frontend/src/pages/editentry/AccumulateAllComponents.jsx, taxonomy-editor-frontend/src/pages/editentry/createURL.jsx
- Remove end slashes while creating URL's
=> fix: Remove end slashes from URL in frontend

.github/workflows/container-build.yml, .github/workflows/container-deploy.yml
There was a problem with CD:
- container image build was not triggered on push to main
- container image deploy did not catch the error.
=> ci: fix workflow

.github/workflows/pull_request.yml
- The Makefile for Taxonomy Editor already contains checks for parser
- Removed separate parser checks from pull_request.yml
=> build: Remove redundant parser checks

.github/workflows/github-projects-for-openfoodfacts-design.yml
- ci: github projects to documentation
=> ci: github projects to documentation

taxonomy-editor-frontend/src/components/LanguageSelectionDialog.jsx, taxonomy-editor-frontend/src/pages/editentry/LanguageSelectionDialog.jsx, taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx
- Select what languages are to be shown in the UI
- #154
=> feat: select shown languages in UI

Makefile
when we run make frontend_quality
see:
- Fixes #188
=> build: avoid loosing build/.empty

taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx
Remember languages that the user selected as "Shown" in the UI with local storage.
=> feat: store languages marked as visible by user in localstorage

doc/introduction/setup-dev.md
=> docs: react live reload

CONTRIBUTING.md
Fix broken link in CONTRIBUTING.md
=> docs: fix setup doc link

taxonomy-editor-frontend/src/components/useFetch.ts, taxonomy-editor-frontend/src/pages/home/index.tsx
- typescript migration. useFetch hook.
=> refactor:  typescript, useFetch hook

README.md
- Add invite link to Open Food Facts
=> docs: Add invite link for Open Food Facts

taxonomy-editor-frontend/src/App.tsx, taxonomy-editor-frontend/src/backend-types/types.ts, taxonomy-editor-frontend/src/pages/go-to-project/index.tsx, taxonomy-editor-frontend/src/pages/home/index.tsx, taxonomy-editor-frontend/src/pages/startproject/index.tsx
- typescript: migrated 'Go to projects ' page to typescript
same UI
=> refactor: typescript, migrated gotoproject page

taxonomy-editor-frontend/src/pages/export/index.tsx
- export page to typescript
Same UI
=> refactor: typescript in export page

taxonomy-editor-frontend/src/pages/startproject/index.tsx
- Fixes a broken link to navigate to all root nodes page.
=> fix: Broken link while starting new project

taxonomy-editor-frontend/src/pages/go-to-project/index.tsx
-  added scrollbar in the table to make it responsive for smaller screen sizes
-  #203
=> fix: #203 added scrollbar in the table for small screen sizes

taxonomy-editor-frontend/src/pages/go-to-project/index.tsx
=> fix: clean duplicate title in project list

taxonomy-editor-frontend/src/pages/export/index.tsx
=> fix: wording in export

.github/workflows/container-deploy.yml
RESTART_POLICY must be set to always on deployments.
=> ci: restart policy must be always on deployment

.env, .github/workflows/container-deploy.yml, backend/editor/github_functions.py, backend/editor/settings.py, docker-compose.yml, taxonomy-editor-frontend/src/App.tsx
- On PR creation via the editor, adds a link to the Taxonomy Editor project in the PR description.
- This introduces a `FRONTEND_URL` environment variable, that must be set for the link to appear correctly.
- Resolves #471
=> feat: add link to the Taxonomy Editor project in PR description

parser/openfoodfacts_taxonomy_parser/parser/parser.py, parser/openfoodfacts_taxonomy_parser/parser/taxonomy_parser.py, parser/tests/data/test_broken_taxonomy.txt, parser/tests/integration/test_parse_unparse_integration.py, parser/tests/integration/test_parser_integration.py
- Don't fail for a single line
- Keep non existing parents as comments
- Keep isolated properties with previous entry
=> feat: make taxonomy more robust

.env, docker-compose.yml
* default to production settings
* add it to every service
=> build: change restart policy

taxonomy-editor-frontend/src/pages/startproject/index.tsx
Simpler names to be easy to read.
=> feat: more readable default project names

.github/workflows/container-deploy.yml
- The deploy workflow wasn't working due to commands being in the old Docker Compose version
=> build: Change docker commands for new version

taxonomy-editor-frontend/src/pages/project/export/index.tsx
- "Additionnally" -> "Additionally"
- 
-
=> fix: Fix typo in PR dialog text
