openfoodfacts/taxonomy-editor

backend/editor/api.py
backend/editor/entries.py

- Adds GET paths `/entry/{entry}/parents` and `/entry/{entry}/children` 
- Used for finding parents and children of a node
- Changed neo4j query to disallow partial updates
- Fixes #33 
- Fixes #40

feat: Add GET paths for parents and children + fix: Update Neo4J query

---

.github/workflows/pull_request.yml

- Parser checks workflow runs for every PR
- It must be run only when any files inside the `parser` directory is changed.

build: Change parser workflow

---

backend/requirements.txt

- Missing library (Unidecode) in requirements.txt

fix: Update requirements.txt for backend

---

backend/editor/entries.py

- Neo4J gives a score of 0 for nodes that don't match sometimes
- To account for that, a "where" clause with "score > 0" must be added in the backend

fix: Add score > 0 condition for search

---

conf/nginx.conf
doc/introduction/setup-dev.md
docker/dev.yml

In dev react tries to open a websocket to the node server (for auto-refresh, I think). This was not supported, now this is.

build: support websocket in dev setup

---

backend/editor/entries.py

Code added normalises the nodes using the normalising function in the API calls of:
1. Created
2. Updated Nodes
3. Updated Nodes Children
- Fixes #79

fix: Normalising Children and New Nodes

---

backend/editor/api.py
backend/editor/entries.py
backend/editor/exceptions.py
backend/editor/github_functions.py
backend/editor/graph_db.py
backend/editor/settings.py
backend/requirements.txt
parser/openfoodfacts_taxonomy_parser/parser.py
parser/openfoodfacts_taxonomy_parser/unparser.py
parser/setup.py
parser/tests/conftest.py
parser/tests/integration/test_parse_unparse_integration.py
parser/tests/integration/test_parser_integration.py
parser/tests/unit/test_parser_unit.py

- Add routes for importing and dumping a taxonomy
- Fixes #71 
- Fixes #83 
- Fixes #84

feat: Add routes for import/export taxonomy

---

.github/labeler.yml

- Added paths for labelling "frontend" changes
- Removed `package-lock.json` from dependencies, since `package.json` is the main dependencies file.

build: Add frontend label to Labeler workflow

---

.env
.github/workflows/container-deploy.yml
conf/nginx.conf
docker-compose.yml

we have to encode API scheme in nginx conf because we are proxying an alrdeay proxied request and loose original scheme.
fixes: https://github.com/openfoodfacts/taxonomy-editor/issues/138

ci: fix API scheme

---

Makefile

build: explicit error when using cmd.exe to run make

---

taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx

2. hide button should work as hiding a long list, not hide it all together
Future:
1. replace autocomplete with Select multiple with checkboxes
3. When there is a language that doesn’t have values we show a button that says ‘Please add translations’ or something and when the user clicks it shows an empty input
4. when the user clicks remove  it goes to 3 (show ‘Please add translations’)
- #154

feat: hide all languages by default in the UI

---

backend/editor/api.py
backend/editor/entries.py
taxonomy-editor-frontend/src/pages/allentries/index.jsx

- Exclude synonyms and stopwords from the `/rootnodes` endpoint as we don't support editing them anyway.
- #173 
- Invalidates - #108

feat: hide synonyms and stopwords in the root nodes page

---

backend/editor/entries.py
taxonomy-editor-frontend/src/backend-types/types.ts
taxonomy-editor-frontend/src/pages/go-to-project/index.tsx

- `/projects` API response is now a flat array . Before it was an array inside another array.
- updated the back and front end.
same UI

refactor: API projects response

---

backend/editor/entries.py
parser/openfoodfacts_taxonomy_parser/parser.py
taxonomy-editor-frontend/src/pages/editentry/AccumulateAllComponents.jsx
taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx

- Removes the tags_str property
- Uses the tags_lc property for creating search indexes
- #219

refactor: Removed tags_str property

---

taxonomy-editor-frontend/src/pages/startproject/index.tsx

- Show feedback when special characters are entered in branch name.
- If there is error, disabled the submit button.
- #168  
- #30

feat: Show feedback when special characters are entered in branch name

---

README.md

``` 
<details><summary><h2> Weekly meetings </h2></summary>
- We e-meet [Tuesdays at 17:00 Paris Time](https://dateful.com/convert/paris-france?t=5pm)
- ![Google Meet](https://img.shields.io/badge/Google%20Meet-00897B?logo=google-meet&logoColor=white) Video call link: https://meet.google.com/xin-bwzm-xvj
- Join by phone: https://tel.meet/nnw-qswu-hza?pin=2111028061202
- Add the Event to your Calendar by [adding the Open Food Facts community calendar to your calendar](https://wiki.openfoodfacts.org/Events)
- [Weekly Agenda](https://docs.google.com/document/d/1tdYkUmoRU8BxFPdCwtewoUi7PV8PmDlXtExOcPYyu-I): please add the Agenda items as early as you can. Make sure to check the Agenda items in advance of the meeting, so that we have the most informed discussions possible. 
- The meeting will …
```

docs: remove weekly meetings

---

taxonomy-editor-frontend/src/pages/root-nodes/index.tsx

User can not choose a node to edit from Nodes page.
To do that, has to go to Search page and click on it. 
Go to https://ui.taxonomy.openfoodfacts.net/states/editstostates/entry
And try to click on an edit button (nothing happens)
Now, on Nodes page, user can click on an edit button to go to node editor.
taxonomy-editor-frontend

fix(taxonomy-editor-frontend): redirect user to node editor when clicking from nodes page

---

backend/editor/api.py
backend/editor/github_functions.py

Add specific messages if Github settings were not added and change some status codes in backend
Some errors raised by backend have a 500 status code intead of having 4XX error.
For example, if a developer forgets to add a Personal Access Token and wants to import a project to edit, the server throws a 500 error instead of 400 error.
- backend/editor

refactor(backend): better error handling in backend

---

taxonomy-editor-frontend/src/components/NodesTableBody.tsx
taxonomy-editor-frontend/src/pages/root-nodes/index.tsx
taxonomy-editor-frontend/src/pages/search/SearchResults.tsx

Create a component for nodes table used in nodes and search pages
- Right now we have quite the same list on root nodes page and search page, we should use the same component to avoid double maintenance.
no visible change
taxonomy-editor-frontend\src\pages\search\SearchResults.tsx
taxonomy-editor-frontend\src\pages\root-nodes\index.tsx

refactor(taxonomy-editor-frontend): Create a component for nodes table

---

parser/openfoodfacts_taxonomy_parser/parser/parser.py

Small follow-up PR to https://github.com/openfoodfacts/taxonomy-editor/pull/318
By updating the node creation query, we speed by about x2 the node creation performance.
So for example, Categories are created in about 15s instead of 25s

feat: Improve node creation performance

---

backend/editor/entries.py
parser/openfoodfacts_taxonomy_parser/parser/parser.py
parser/openfoodfacts_taxonomy_parser/parser/taxonomy_parser.py
parser/openfoodfacts_taxonomy_parser/unparser.py
parser/tests/integration/test_parse_unparse_integration.py

Currently, when we export back the taxonomy to a .txt file, the parent order is random and not deterministic
To solve this, we are now keeping track of the parent order in the original file
In the future, we may want to impose the parent order (alphabetical order for example) but right now, it would result in too big .txt file diff
https://github.com/orgs/openfoodfacts/projects/103/views/1?pane=issue&itemId=48206861

feat: Add parent order determinism

---

parser/openfoodfacts_taxonomy_parser/parser/logger.py
taxonomy-editor-frontend/src/pages/errors/index.jsx

Quick win to improve the errors page.
Backend:
- changed ellipsis from 20 characters to 1000 characters in the errors
Frontend:
- errors table now uses all width of the page
- default page size is now 50 instead of 5
- added an alert to indicate that the errors must be fixed via Github and not via the editor
- fixed typo and improved layout
Related to #340

feat: improve errors page

---

parser/openfoodfacts_taxonomy_parser/parser/taxonomy_parser.py
parser/openfoodfacts_taxonomy_parser/unparser.py
parser/tests/data/test.txt
parser/tests/integration/test_parse_unparse_integration.py
parser/tests/integration/test_parser_integration.py

Currently, the parser reads the raw stopwords from the input taxonomy file, normalizes them and stores only these normalized stopwords in the Neo4J database.
This PR makes the parser store the raw stopwords also, to be able to rewrite them at export.
**WARNING: This PR will make previously open projects impossible to export.**
See issue #357

feat: store raw stopwords and rewrite them at export

---

taxonomy-editor-frontend/src/pages/errors/index.jsx

###Current situation
if the project has no error while parsing and we naviagte to errors page, this is what we see :
###TO-DO
if no errors, the table and warning are not displayed.
[https://github.com/openfoodfacts/taxonomy-editor/issues/383](url)

fix(frontend): Handle no error case on errors page

---

taxonomy-editor-frontend/src/constants.js
taxonomy-editor-frontend/src/pages/go-to-project/index.tsx

Currently, there is an unintended capability to edit languages and countries taxonomies in the editor. This behavior needs correction.
[https://github.com/openfoodfacts/taxonomy-editor/issues/376](issue376)

fix(frontend): Remove Countries and Languages from editable taxonomies

---

backend/editor/entries.py
parser/openfoodfacts_taxonomy_parser/parser/taxonomy_parser.py
parser/openfoodfacts_taxonomy_parser/utils.py

This PR fixes the fact that the stopwords were not removed during normalization of the tags outside the parser (i.e during node update, or node creation).
- Added an optional `stopwords` parameter (dict) to the `normalize_text` utils function, in order to remove stopwords from a given text.
- Modified the `update_node` controller to remove the stopwords during normalization thanks to the new parameter
- Refactored the parser to make it use the `normalize_text` utils function instead of its own method defined in its class
Fixes #367

fix(backend,parser): remove stopwords from normalized tags on node update

---

parser/openfoodfacts_taxonomy_parser/parser/parser.py
parser/openfoodfacts_taxonomy_parser/parser/taxonomy_parser.py

- Taxonomy parser now checks for valid child links and logs out the missing child links in the parsing errors
- Partly fixes: https://github.com/openfoodfacts/taxonomy-editor/issues/356

chore: Log more expressive errors for missing child links

---

taxonomy-editor-frontend/src/pages/editentry/ListAllEntryProperties.jsx

1. When adding a property and confirming the row, the new property is not instantly visible in the table.
2. After adding a property, confirming the row, and saving changes, the new property is visible in the table
3. When deleting a property and confirming, the row is not instantly removed from the table.
4. After deleting a property, confirming, and saving changes, the deleted property is not visible anymore
5. Editing properties is working correctly if we only edit the value, otherwise it doesn't work well
https://github.com/openfoodfacts/taxonomy-editor/assets/106757110/e7ef1631-3c62-4e80-b24c-838ee8f9ccb5
https://github.com/openfoodfacts/taxonomy-editor/assets/106757110/69f9dcba-9ec2-4f07-bca8-8fa413c280ed
I've changed the style of the table and removed pagination to help users to …

fix(frontend): Enhance Edition of Properties for a Node

---

backend/editor/api.py
backend/editor/controllers/node_controller.py
backend/editor/entries.py
backend/editor/models/node_models.py
taxonomy-editor-frontend/src/components/CreateNodeDialogContent.tsx
taxonomy-editor-frontend/src/pages/root-nodes/index.tsx

- Fixes the `create_node` function in the backend, which was not creating all necessary properties of an entry node, and was making it impossible to export a project where the user had added a new node.
- Fixes #382

fix(backend): fix create_node function

---

taxonomy-editor-frontend/src/pages/editentry/ListEntryChildren.tsx

In an entry's page, we can add new children with the + button:
However, if there are no children currently, this button is hidden:
The button is displayed in all cases.
https://github.com/openfoodfacts/taxonomy-editor/issues/395

fix(frontend): enable child creation even if no children in entry

---

taxonomy-editor-frontend/src/pages/editentry/ListEntryChildren.tsx
taxonomy-editor-frontend/src/pages/editentry/ListEntryParents.tsx

- Adds a `flex-wrap` to make children and parents wrap on multiple lines instead of overflowing on the side of one line
- Fixes #407

fix(frontend): fix children and parents overflow

---

taxonomy-editor-frontend/src/pages/root-nodes/index.tsx

- Fixes root nodes page infinite loading when project has status EXPORTED. Project having this status now disables the loading.
- Fixes #412

fix(frontend): fix root nodes page infinite loading when project exported

---

taxonomy-editor-frontend/src/pages/export/index.tsx

Currently the contributor is not encouraged to watch the PR (s)he just exported on Github.
[- issue 410](https://github.com/openfoodfacts/taxonomy-editor/issues/410#issue-2135855496)

feat(frontend): Reword export message

---

backend/editor/api.py
backend/editor/entries.py
backend/editor/github_functions.py
backend/editor/models/project_models.py
backend/tests/test_api.py
taxonomy-editor-frontend/src/backend-types/types.ts
taxonomy-editor-frontend/src/pages/go-to-project/index.tsx
taxonomy-editor-frontend/src/pages/startproject/index.tsx

Previously, taxonomy projects lacked an explicit owner, leading to ambiguity regarding project ownership. This PR addresses this gap by introducing functionality to specify and display the owner's name for each project.
TO-DO :
when importing a project, the user has to indicate a name.
the author name is displayed in the existing projects table
[- issue 389](https://github.com/openfoodfacts/taxonomy-editor/issues/389)
[- issue 390](https://github.com/openfoodfacts/taxonomy-editor/issues/390)

feat(frontend,backend): Add a owner to a project

---

taxonomy-editor-frontend/src/components/ResponsiveAppBar.tsx

I've changed the Logo navigation to default '/' instead of `https://ui.taxonomy.openfoodfacts.net/`.
Used `Link` from `react-router-dom`
#419

fix: update logo link to default /

---

backend/editor/api.py
backend/editor/models/node_models.py

- This PR fixes the bug that appears when the user tries to create a new node from the root nodes page.
- The issue was that for some reason, `NodeType.ENTRY` is not converted to its corresponding value (see error below). So I've decided for now to hard-code the "ENTRY" value, even if it's not optimal.
- Fixes #444

fix(backend): error on node creation from root nodes

---

backend/editor/models/search_models.py
backend/openapi/openapi.json
taxonomy-editor-frontend/src/client/index.ts
taxonomy-editor-frontend/src/client/models/EntryNodeSearchResult.ts
taxonomy-editor-frontend/src/client/models/PropertyFilterSearchTerm.ts

- Add the property filter to the search API
- The format is  `property:filter_value` where the filter value is in the format `not:inherited:property_name:lc:property_value`
`not:` and `inherited:` and `:property_value` are optional.

feat: add property filter to search API

---

taxonomy-editor-frontend/src/pages/project/editentry/AccumulateAllComponents.tsx
taxonomy-editor-frontend/src/pages/project/editentry/ListEntryChildren.tsx

Currently, users can navigate to a child node while editing a parent node without saving changes, resulting in a potential 404 error if the child node is newly created. 
Additionally, clicking on a child node before saving changes can lead to the loss of unsaved modifications. 
To prevent this, I have disabled the ability to navigate to a child node if this node has been newly created without saving. 
Furthermore, I have implemented a warning message to inform users about why they cannot proceed to the child node : "You've just created a new child. To navigate to it, please ensure your changes are saved first."
There is another warning massage when whatever changes have not been saved : "Changes are pending and have not been saved. Please save your changes before navigating to any child …

fix(frontend): Prevent users from navigating to child with unsaved changes

---

taxonomy-editor-frontend/src/pages/project/editentry/ListEntryChildren.tsx
taxonomy-editor-frontend/src/pages/project/search/FiltersArea.tsx

From Alizarine: when I want to select a language in the "translated into" dropdown menu, the languages are not in the alphabetic order (see screenshot). It can be confusing but it's not a big deal.

fix: sort languages in search filters

---

parser/openfoodfacts_taxonomy_parser/unparser.py

Fix language order to match taxonomy linter preferred order.
Fixes: #511

fix: language order as we dump taxonomies

---

Makefile
parser/openfoodfacts_taxonomy_parser/parser/taxonomy_parser.py
parser/openfoodfacts_taxonomy_parser/unparser.py
parser/tests/data/test_property_confused_lang.txt
parser/tests/integration/test_parser_integration.py

We are confusing "web:en: https://xxx.com" with a synonyms entry…

fix: avoid confusing language prefixes and property names

---

backend/sample/test.txt
backend/tests/data/test.txt
parser/openfoodfacts_taxonomy_parser/parser/taxonomy_parser.py
parser/openfoodfacts_taxonomy_parser/unparser.py
parser/tests/data/test.txt
parser/tests/data/test_external1.txt
parser/tests/integration/test_parse_unparse_integration.py
parser/tests/unit/test_parser_unit.py

This is another important part to normalize: white spaces at start of line.
Enables being consistent.

fix: add a space after line identifier

---

parser/openfoodfacts_taxonomy_parser/parser/taxonomy_parser.py
parser/openfoodfacts_taxonomy_parser/utils.py

We were keeping "lower commas" in text when we parse taxonomies, and also alter parenthesis or commas.
It's problematic when we create the final PR because it induces unwanted changes.

fix: avoid altering original entries at parsing time

---

taxonomy-editor-frontend/src/components/EntryNodesTableBody.tsx
taxonomy-editor-frontend/src/pages/project/errors/index.tsx

Fix a warning in the console because our tables are not well formed on search results page and errors page.

fix: bad tables dom on errors and search results

---

backend/editor/utils.py
taxonomy-editor-frontend/src/constants.ts

Added beauty categories and labels.

feat: first beauty and product taxonomies
